import argparse
import os

from datasets import load_dataset
from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    Trainer,
    TrainingArguments,
)

LABEL_LIST = ["O", "B-ANIMAL", "I-ANIMAL"]
ID2LABEL = {i: label for i, label in enumerate(LABEL_LIST)}
LABEL2ID = {label: i for i, label in enumerate(LABEL_LIST)}

def tokenize_and_align_labels(examples, tokenizer):
    """
    Tokenizes input texts and aligns the NER tags with the subword tokens 
    generated by the BERT/RoBERTa tokenizer.
    """
    tokenized_inputs = tokenizer(
        examples["tokens"], truncation=True, is_split_into_words=True, max_length=128
    )

    labels = []
    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100) # PyTorch ignores -100 in CrossEntropyLoss
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(label[word_idx] if True else -100)
            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

def main():
    parser = argparse.ArgumentParser(description="Fine-tune a NER model for animal extraction")
    parser.add_argument('--model_name', type=str, default='dslim/bert-base-NER', help='Base HF model name')
    parser.add_argument('--data_path', type=str, required=True, help='Path to the dataset (JSON format)')
    parser.add_argument('--output_path', type=str, default='models/ner_animal', help='Directory to save the model')
    parser.add_argument('--epochs', type=int, default=3, help='Number of training epochs')
    
    args = parser.parse_args()

    tokenizer = AutoTokenizer.from_pretrained(args.model_name, add_prefix_space=True)
    
    model = AutoModelForTokenClassification.from_pretrained(
        args.model_name,
        num_labels=len(LABEL_LIST),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
        ignore_mismatched_sizes=True 
    )

    dataset = load_dataset("json", data_files={"train": args.data_path})
    
    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x, tokenizer),
        batched=True,
        remove_columns=dataset["train"].column_names
    )

    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

    training_args = TrainingArguments(
        output_dir=args.output_path,
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        num_train_epochs=args.epochs,
        weight_decay=0.01,
        save_strategy="epoch",
        logging_steps=10,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    trainer.train()
    trainer.save_model(os.path.join(args.output_path, "best_model"))

if __name__ == '__main__':
    main()